[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 20

[theme]
base = "light"
primaryColor = "#1d3557"
backgroundColor = "#f7f1e8"
secondaryBackgroundColor = "#ffffff"
textColor = "#14213d"
font = "sans serif"
